# Generated by Django 5.1.1 on 2024-10-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_actual',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Actual'),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_anterior',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Anterior'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mys.shop', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3, null=True, verbose_name='Tamaño'),
        ),
    ]
