# Generated by Django 5.1.1 on 2024-11-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0004_remove_user_address_product_color_product_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, null=True, verbose_name='Producto URL'),
        ),
    ]
