# Generated by Django 5.1.1 on 2024-11-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0005_product_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_colores',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_marcas',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_tipos',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
