# Generated by Django 5.1.1 on 2024-11-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0008_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
