# Generated by Django 5.1.1 on 2024-11-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0012_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tipo',
            field=models.JSONField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
